[tool.poetry]
name = "statapp"
version = "0.1.0"
description = ""
authors = [
    "Maxim Slipenko <statapp@maks1ms.addy.io>"
]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
pyside6 = "^6.4"
pandas = "^2.1.1"
numpy = "^1.26.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
